### ISSUE TITLE
Exception while loading env

### ISSUE THREAD

**Issue by rdkdd** [spiceqa/tp-spice#40]
After test case is executed an exception is thrown.
From a log file:

```
Exception thrown while loading env
(AttributeError("'VM' object has no attribute 'name'",), <class virttest.qemu_monitor.HumanMonitor at 0x3560a10>, (<virttest.qemu_vm.VM object at 0x4889850>, 'hmp1', '/var/tmp/avocado_MwHWdu/monitor-hmp1-20161125-145215-X5Ef8dfb', False))
Creating new, empty env file
Exception AttributeError: "HumanMonitor instance has no attribute 'open_log_files'" in <bound method HumanMonitor.__del__ of <virttest.qemu_monitor.HumanMonitor instance at 0x49990e0>> ignored
```

Avocado run does not finish properly.
I am not sure if it is tp-spice or avocado issue.

**Comment by Andrei-Stepanov** [comment]
@rdkdd : Any idea ow to reproduce this one?

**Comment by rdkdd** [comment]
Just try to run any testcase.

**Comment by rdkdd** [comment]
The problem seems to be corrected. After upgrade of Avocado-VT to 46.0 no such error emerged again.
